Webproject/Webproject/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Webproject.Controllers
{
    public class SchoolController : Controller
    {
        string constr2 = @"Data Source=(LocalDB)\MSSQLLocalDB;" + "AttachDbFilename=|DataDirectory|BlueAssistDB.mdf;" + "Integrated Security=True";
        string constr = @"Data Source=localhost;Initial Catalog=DepChatBot2;User ID=Wiwi;Password=0919794175;";
        // GET: School
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(string account, string password)
        {
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select Count(*) from School Where School_account=N'{0}' AND School_password=N'{1}'", account,password);
            con1.Open();
            SqlCommand cmd1 = new SqlCommand(sql1, con1);
            if ((int)cmd1.ExecuteScalar() == 1)
            {
                Session["account"] = account;
                Session["password"] = password;
                return View("Index","_Layout-School");
            }
            return View();
        }
        public ActionResult SocialworkerVerification()
        {
            return View("SocialworkerVerification", "_Layout-School");
        }
        [HttpPost]
        public ActionResult SocialworkerVerification(string verification)
        {
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;

            string sql1 = string.Format("select School_Id from School Where School_account=N'{0}' AND School_password=N'{1}'", Session["account"],Session["password"]);
            con1.Open();
            SqlCommand cmd1 = new SqlCommand(sql1, con1);
            int School_Id = (int)cmd1.ExecuteScalar();

            string sql2 = string.Format("Insert into Verification ( School_Id,Verification) values('{0}','{1}')", School_Id, verification);
            SqlCommand cmd2 = new SqlCommand(sql2, con1);
            cmd2.ExecuteNonQuery();
            con1.Close();

            ViewBag.verification = verification;
            return View();
        }
        public ActionResult StudentVerification()
        {
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select School_Id from School Where School_account=N'{0}' AND School_password=N'{1}'", Session["account"], Session["password"]);
            con1.Open();
            SqlCommand cmd1 = new SqlCommand(sql1, con1);
            int School_Id = (int)cmd1.ExecuteScalar();
            string sql2 = string.Format("select Socialworker_name,Socialworker_account from Socialworker where School_id={0}",School_Id);
            SqlDataAdapter adp = new SqlDataAdapter(sql2, con1);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            con1.Close();
            return View("StudentVerification", "_Layout-School", ds.Tables[0]);
        }
        [HttpPost]
        public ActionResult StudentVerification(string socialworker, string verification)
        {
            string[] s = socialworker.Split(',');
           
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;

            string sql1 = string.Format("select Socialworker_Id from Socialworker Where Socialworker_account=N'{0}' ", s[1]);
            con1.Open();
            SqlCommand cmd1 = new SqlCommand(sql1, con1);
            int Socialworker_Id = (int)cmd1.ExecuteScalar();


            string sql2 = string.Format("select School_Id from School Where School_account=N'{0}' AND School_password=N'{1}'", Session["account"], Session["password"]);
            SqlCommand cmd2 = new SqlCommand(sql2, con1);
            int School_Id = (int)cmd2.ExecuteScalar();

            string sql3 = string.Format("Insert into Verification ( School_Id,Socialworker_Id,Verification) values('{0}','{1}','{2}')", School_Id, Socialworker_Id, verification);
            SqlCommand cmd3 = new SqlCommand(sql3, con1);
            cmd3.ExecuteNonQuery();
            con1.Close();

            return Redirect("SearchVerification");
        }
        public ActionResult SearchVerification()
        {
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select School_Id from School Where School_account=N'{0}' AND School_password=N'{1}'", Session["account"], Session["password"]);
            con1.Open();
            SqlCommand cmd1 = new SqlCommand(sql1, con1);
            int School_Id = (int)cmd1.ExecuteScalar();
            string sql2 = string.Format("select * from Verification right join Socialworker on Verification.Socialworker_Id = Socialworker.Socialworker_Id where Verification.School_id={0}", School_Id);
            SqlDataAdapter adp = new SqlDataAdapter(sql2, con1);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            con1.Close();
            return View("SearchVerification", "_Layout-School", ds.Tables[0]);
        }
        public ActionResult SocialworkerManagement()
        {
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            con1.Open();
            string sql1 = string.Format("select School_Id from School Where School_account=N'{0}' AND School_password=N'{1}'", Session["account"], Session["password"]);
            SqlCommand cmd1 = new SqlCommand(sql1, con1);
            int School_Id = (int)cmd1.ExecuteScalar();

            string sql2 = string.Format("select * from Socialworker where School_id = '{0}'", School_Id);
            SqlDataAdapter adp = new SqlDataAdapter(sql2, con1);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            con1.Close();
            return View("SocialworkerManagement", "_Layout-School", ds.Tables[0]);
        }
        public ActionResult ShowStudent(int id) {
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select * from Student where Socialworker_id = '{0}'", id);
            SqlDataAdapter adp = new SqlDataAdapter(sql1, con1);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            con1.Close();
            return View("ShowStudent", "_Layout-School", ds.Tables[0]);
        }
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.RemoveAll();
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);
            HttpCookie cookie2 = new HttpCookie("ASP.NET_SessionId", "");
            cookie2.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie2);
            return RedirectToAction("Index", "Home");
        }
    }
}

Webproject/Webproject/Controllers/StudentController.cs
using System.Linq;
using System.Web;
using System.Web.Mvc;
using isRock.LineLoginV21;
using Newtonsoft.Json;
using System.Data;
using System.Data.SqlClient;
using System.Diagnostics;
using System;
using System.Web.Security;
using System.Net.Mail;

//final

namespace Webproject.Controllers
{
    public class StudentController : Controller
    {
        string LineLogin = "https://54d61a5fb0e8.ngrok.io";         // LineLogin_Callback_url
        string Client_id = "1655812280";                            // LineLogin_Client_id
        string Client_secret = "d3b069e868ece1d5e46937b2bf16ee41";  // LineLogin_Client_secret
        string Bot_Basic_id = "@145ltdwx";                          // LineLogin_Bot_Basic_id
        // GET: Student
        public ActionResult Index()
        {
            return View("Index", "_Layout-Student");
        }
        string constr2 = @"Data Source=(LocalDB)\MSSQLLocalDB;" + "AttachDbFilename=|DataDirectory|BlueAssistDB.mdf;" + "Integrated Security=True";
        string constr = @"Data Source=localhost;Initial Catalog=DepChatBot2;User ID=Wiwi;Password=0919794175;";
        public class Lineget
        {
            public string displayName { get; set; }

            public string userId { get; set; }

            public string pictureUrl { get; set; }

            public string statusMessage { get; set; }
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Callback()
        {
            //取得返回的code
            var code = Request.QueryString["code"];
            if (code == null)
            {
                ViewBag.access_token = "沒有正確的code...";
                return View("Index", "_Layout-Student");
            }
            //從Code取回toke
            var token = Utility.GetTokenFromCode(code,
                Client_id,  //TODO:請更正為你自己的 client_id
                Client_secret, //TODO:請更正為你自己的 client_secret
                LineLogin+"/Student/Callback");  //LineLogin 位置
            //利用access_token取得用戶資料
            var user = Utility.GetUserProfile(token.access_token);
            //利用id_token取得Claim資料
            var JwtSecurityToken = new System.IdentityModel.Tokens.Jwt.JwtSecurityToken(token.id_token);
            var email = "";
            //如果有email
            if (JwtSecurityToken.Claims.ToList().Find(c => c.Type == "email") != null)
                email = JwtSecurityToken.Claims.First(c => c.Type == "email").Value;
            Lineget get1 = JsonConvert.DeserializeObject<Lineget>(Newtonsoft.Json.JsonConvert.SerializeObject(user));
            Session["Email"] = email;
            Session["userID"] = get1.userId;
            Session["token"] = token.access_token;
            Session["username"] = get1.displayName;
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select COUNT(*) from Student  where Student_userID ='{0}'", get1.userId);
            con1.Open();
            SqlCommand cmd1 = new SqlCommand(sql1, con1);

            int _count = (int)cmd1.ExecuteScalar();
            if (_count == 1)
            {
                con1.Close();
                Debug.WriteLine("有帳號了");
                return View("Index", "_Layout-Student");
            }
            else
            {
                con1.Close();
                return Redirect("~/Student/Create");
            }
        }
        public ActionResult Create()
        {
            ViewBag.name = Session["username"];
            ViewBag.token = Session["token"];
            ViewBag.email = Session["Email"];
            ViewBag.userid = Session["userID"];
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select School_name from School");
            SqlDataAdapter adp = new SqlDataAdapter(sql1, con1);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            return View("Create",ds.Tables[0]);
        }
        [HttpPost]
        public ActionResult Create(string name,string token,string email,string userid,int gender,string birthday,string guardian_name,string guardian_phnumber,
            string teacher,string sclass,string IDNumber ,string LineID,string verification, string SchoolName)
        {
             Debug.WriteLine(verification);
             Debug.WriteLine(SchoolName);
             SqlConnection con1 = new SqlConnection();
             con1.ConnectionString = constr;
             con1.Open();
             string sql1 = string.Format("select Count(*) from Verification Where Verification =N'{0}'", verification);
             SqlCommand cmd = new SqlCommand(sql1, con1);
             if ((int)cmd.ExecuteScalar() == 1)
             {
                 string sql2 = string.Format("select School_Id,Socialworker_Id from Verification Where Verification =N'{0}'", verification);
                 SqlDataAdapter adp = new SqlDataAdapter(sql2, con1);
                 DataSet ds = new DataSet();
                 adp.Fill(ds);
                 foreach (DataRow datarow in ds.Tables[0].Rows)
                 {
                    int Socialworker_id = (int)datarow["Socialworker_Id"];
                    int School_id = (int)datarow["School_Id"];
                    string sql3 = string.Format("Insert into Student (School_id,Student_token,Student_Email,Student_name,Student_gender,Student_birthday,Student_guardian_name,Student_guardian_phnumber,Student_teacher,Student_class," +
                        "Student_IDNumber,Socialworker_id,Student_userID,Counseling,LineId) " + "values('{0}',N'{1}','{2}',N'{3}','{4}','{5}','{6}','{7}','{8}','{9}','{10}','{11}','{12}','{13}','{14}')"
                        , School_id, token, email, name, gender, birthday, guardian_name, guardian_phnumber, teacher, sclass, IDNumber, Socialworker_id, userid, 0, LineID);
                    SqlCommand cmd1 = new SqlCommand(sql3, con1);
                    cmd1.ExecuteNonQuery();
                    con1.Close();
                 }
                 return View("Index", "_Layout-Student");
             }
             else
             {
                 string sql4 = string.Format("Insert into Student(Student_token,Student_Email,Student_name,Student_gender,Student_birthday,Student_userID,Counseling,LineId)" +
                        "values('{0}',N'{1}',N'{2}',N'{3}','{4}','{5}','{6}','{7}')",token, email, name, gender, birthday, userid, 1, LineID);
                 SqlCommand cmd2 = new SqlCommand(sql4, con1);
                 cmd2.ExecuteNonQuery();
                 con1.Close();
                 return View("Index", "_Layout-Student");
             }

            /*con1.Close();
            ViewBag.err = "請重新輸入";
            return Redirect("Create");*/

            /*   string sql1 = string.Format("select School_Id from School Where School_name=N'{0}'", SchoolName);
               con1.Open();
               SqlCommand cmd1 = new SqlCommand(sql1, con1);
               int School_ID = (int)cmd1.ExecuteScalar();


               string sql2 = string.Format("select Socialworker_Id from Socialworker where School_id ='{0}'", School_ID);
               SqlCommand cmd2 = new SqlCommand(sql2, con1);
               int Socailworker_ID = (int)cmd2.ExecuteScalar();*/

            /* string sql3 = string.Format("Insert into Student (School_id,Student_token,Student_Email,Student_name,Student_gender,Student_birthday,Student_guardian_name,Student_guardian_phnumber,Student_teacher,Student_class," +
                 "Student_IDNumber,Socialworker_id,Student_userID,Counseling,LineId) " + "values('{0}',N'{1}','{2}',N'{3}','{4}','{5}','{6}','{7}','{8}','{9}','{10}','{11}','{12}','{13}','{14}')"
                 , School_ID, token, email, name, gender, birthday, guardian_name, guardian_phnumber, teacher, sclass, IDNumber, Socailworker_ID, userid, 0, LineID);
             SqlCommand cmd = new SqlCommand(sql3, con1);
             cmd.ExecuteNonQuery();
             con1.Close();*/
        }
        public ActionResult Record()
        {
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select Student_name from Student Where Student_userID = N'{0}'",Session["userID"]);
            con1.Open();
            SqlCommand cmd1 = new SqlCommand(sql1, con1);
            string name = (string)cmd1.ExecuteScalar();
            Debug.WriteLine(name);
            ViewBag.name = name;
            con1.Close();
            return View("Record", "_Layout-Student");
        }
        [HttpPost]
        public ActionResult Record(int AssistClass, string content)
        {
            DateTime time = DateTime.Now;
            SqlConnection con1 = new SqlConnection();
            con1.ConnectionString = constr;
            string sql1 = string.Format("select Student_Id,Socialworker_id from Student Where Student_userID  =N'{0}'", Session["userID"]);
            con1.Open();
            SqlDataAdapter adp = new SqlDataAdapter(sql1, con1);
            DataSet ds = new DataSet();
            adp.Fill(ds);
            foreach (DataRow datarow in ds.Tables[0].Rows)
            {
                int Socialworker_id = (int)datarow["Socialworker_id"];
                int Student_id = (int)datarow["Student_Id"];
                string sql3 = string.Format("Insert into Record (AssistClass,Socialworker_id,Student_id,Student_content,Student_requestTime) values('{0}','{1}','{2}','{3}','{4}')", AssistClass, Socialworker_id, Student_id, content, time.ToString("yyyy-MM-dd HH:mm"));
                SqlCommand cmd = new SqlCommand(sql3, con1);
                cmd.ExecuteNonQuery();
                con1.Close();
            }

            Session.Add("checkRecord", "");
            Session["checkRecord"] = "true";

            return View("Index", "_Layout-Student");
        }
        public ActionResult SearchRecord()

Webproject/Webproject/Views/Shared/_Layout-School.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "School", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "School")</li>
                    <li>@Html.ActionLink("社工驗證碼", "SocialworkerVerification", "School")</li>
                    <li>@Html.ActionLink("學生驗證碼", "StudentVerification", "School")</li>
                    <li>@Html.ActionLink("查詢學生驗證碼", "SearchVerification", "School")</li>
                    <li>@Html.ActionLink("社工管理", "SocialworkerManagement", "School")</li>
                    <li>@Html.ActionLink("登出", "Logout", "School")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Webproject/Webproject/Views/Shared/_Layout-Socialworker.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Socialworker", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Socialworker")</li>
                    <li>@Html.ActionLink("填寫回報日誌", "ShowStudent", "Socialworker")</li>
                    <li>@Html.ActionLink("登出", "Logout", "Socialworker")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Webproject/Webproject/Views/Shared/_Layout-Student.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Student", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Student")</li>
                    <li>@Html.ActionLink("量表測試", "Scale", "Student")</li>
                    <li>@Html.ActionLink("查看量表", "SearchScale", "Student")</li>
                    <li>@Html.ActionLink("查詢回報", "SearchRecord", "Student")</li>
                    <li>@Html.ActionLink("回報", "Record", "Student")</li>
                    <li>@Html.ActionLink("登出", "Logout", "Student")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Webproject/Webproject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("學生登入", "Login", "Student")</li>
                    <li>@Html.ActionLink("校方登入", "Login", "School")</li>
                    <li>@Html.ActionLink("社工註冊", "Create", "Socialworker")</li>
                    <li>@Html.ActionLink("社工登入", "Login", "Socialworker")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>